[package]
name = "sample-rs-engine"
version = "0.1.0"
edition = "2024"
description = "Backend engine for audio sample processing."

[dependencies]
cpal.workspace = true
crossbeam-channel = "0.5.16"
ringbuf = "0.5.1"
slab = "0.4.12"
tracing.workspace = true
triple_buffer = "9.0.0"
sample-rs-sound = { path = "../sound/" }
